apiVersion: v1
kind: Secret
metadata:
  name: health-tracker-secrets
  namespace: default
type: Opaque
stringData:
  GROQ_API_KEY: "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"
  MONGODB_URI: "mongodb+srv://asmaghalleb6_db_user:asmaghallebdevops@clusterdevops.exdikw5.mongodb.net/healthdb?retryWrites=true&w=majority"
  JWT_SECRET: "your-super-secret-jwt-key-change-in-production-2024"
